spring:
  application:
    name: user
  data:
    mongodb:
      database: users
      uri: 'mongodb+srv://${USER_DB}:${PASSWORD_DB}@${ATLAS_CLUSTER}/?retryWrites=true&w=majority&appName=AtlasCluster'

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG